name: Scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: "25 17 * * 1"
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  scorecard:
    name: OSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
