name: Scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: "25 17 * * 1"
  push:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    name: OSSF Scorecard
    runs-on: ubuntu-latest
    steps:
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
